function transformTest(postmanTest, groupId) {
	const checkName = postmanTest.name;
	const request = postmanTest.request;
	const requestMethod = request.method;
	const requestUrl = request.url;
	let requestUrlRaw = requestUrl.raw;

	const urlVariables = requestUrlRaw.match(':[a-zA-Z]*');
	if (urlVariables && requestUrl.variable) {
		for (variable of requestUrl.variable) {
			requestUrlRaw = requestUrlRaw.replace(':' + variable.key, variable.value);
		}
	}

	let requestBodyMode;
	let requestBody;
	switch (postmanTest.request.body?.mode) {
		case 'raw':
			requestBodyMode = 'RAW';
			requestBody = postmanTest.request.body.raw;
			break;
		case 'urlencoded':
			requestBodyMode = 'FORM';
			const items = postmanTest.request.body.urlencoded.items;
			let bodyString = '';
			for (let item in items) {
				bodyString.concat(item.key, '&', item.value);
			}
			requestBody = bodyString;
			break;
		case 'file':
			console.log("WARNING: Unsupported body format 'file', defaulting to 'raw'. This check might fail.");
			requestBodyMode = 'RAW';
			requestBody = postmanTest.request.body.file;
			break;
		case 'formdata':
			console.log("WARNING: Unsupported body format 'formdata', defaulting to 'raw'. This check might fail.");
			requestBodyMode = 'RAW';
			requestBody = postmanTest.request.body.raw;
			break;
		case 'graphql':
			requestBodyMode = 'GRAPHQL';
			requestBody = postmanTest.request.body.graphql;
			break;
	}

	const oldRequestHeaders = postmanTest.request.header;
	const postmanDefaultHeaders = [
		// autogenerated by Postman
		{ key: 'User-Agent', value: 'Checkly' }, // changed to Checkly
		{ key: 'Accept', value: '*/*' },
		{ key: 'Accept-Encoding', value: 'gzip, deflate, br' },
		{ key: 'Connection', value: 'keep-alive' },
	];
	const newRequestHeaders = postmanDefaultHeaders;
	const oldQueryParams = postmanTest.request.url.query;
	const newQueryParams = [];

	for (let oldHeader of oldRequestHeaders) {
		if (oldHeader.key) {
			const newHeader = {
				key: oldHeader.key,
				value: oldHeader.value,
			};
			newRequestHeaders.push(newHeader);
		}
	}

	if (oldQueryParams) {
		for (let oldQueryParam of oldQueryParams) {
			if (!oldQueryParam.disabled) {
				const newQueryParam = {
					key: oldQueryParam.key,
					value: oldQueryParam.value,
				};
				newQueryParams.push(newQueryParam);
			}
		}
	}

	let basicAuthUsername = '';
	let basicAuthPassword = '';
	if (request.auth?.basic) {
		basicAuthUsername = request.auth.basic[0]?.value;
		basicAuthPassword = request.auth.basic[0]?.value;
	}

	return (finishedCheck = {
		name: checkName,
		groupId: groupId,
		checkType: 'API',
		frequency: 10,
		activated: true,
		muted: false,
		doubleCheck: true,
		sslCheck: false,
		shouldFail: false,
		locations: ['us-east-1', 'eu-central-1'],
		request: {
			method: requestMethod,
			url: requestUrlRaw,
			followRedirects: true,
			body: requestBody,
			bodyType: requestBodyMode,
			headers: newRequestHeaders,
			queryParameters: newQueryParams,
			assertions: [],
			basicAuth: {
				username: basicAuthUsername,
				password: basicAuthPassword,
			},
		},
		alertSettings: {
			escalationType: 'RUN_BASED',
			runBasedEscalation: {
				failedRunThreshold: 1,
			},
			timeBasedEscalation: {
				minutesFailingThreshold: 5,
			},
			reminders: {
				amount: 0,
				interval: 5,
			},
			sslCertificates: {
				enabled: true,
				alertThreshold: 30,
			},
		},
		useGlobalAlertSettings: true,
		degradedResponseTime: 10000,
		maxResponseTime: 20000,
	});
}

function transformFolder(postmanFolder) {
	return {
		name: postmanFolder.name,
		activated: true,
		muted: false,
		sslCheck: false,
		doubleCheck: true,
		locations: ['us-east-1', 'eu-central-1'],
		alertSettings: {
			escalationType: 'RUN_BASED',
			runBasedEscalation: {
				failedRunThreshold: 1,
			},
			timeBasedEscalation: {
				minutesFailingThreshold: 5,
			},
			reminders: {
				amount: 0,
				interval: 5,
			},
			sslCertificates: {
				enabled: true,
				alertThreshold: 30,
			},
		},
		alertChannelSubscriptions: [],
		useGlobalAlertSettings: true,
	};
}

module.exports = {
	transformFolder: transformFolder,
	transformTest: transformTest,
};
